import "server-only";

import type { HomePageContent } from "@/types/content";

export const fallbackHomePageContent: HomePageContent = {
  hero: {
    slides: [
      {
        id: "hero-slide-clinical",
        announcement: "Nueva colección de temporada disponible",
        eyebrow: "Dermatología curada",
        title: "Skincare clínico respaldado por dermatólogos",
        subtitle:
          "Descubre rutinas probadas en clínica para resultados visibles desde el primer mes. Productos formulados con ingredientes de grado médico.",
        supportingBadge: "Nueva colección",
        primaryCta: {
          label: "Explorar la selección",
          href: "#featured-products",
        },
        secondaryCta: {
          label: "Ver categorías y necesidades",
          href: "#featured-categories",
        },
        media: null,
      },
      {
        id: "hero-slide-campaign",
        announcement: "Ofertas de temporada por tiempo limitado",
        eyebrow: "Campaña en portada",
        title: "Tu piel merece lo mejor",
        subtitle:
          "Aprovecha descuentos exclusivos en rutinas completas de cuidado dermatológico. Stock limitado por temporada.",
        supportingBadge: "Ofertas especiales",
        primaryCta: {
          label: "Ver campaña destacada",
          href: "#featured-campaign",
        },
        secondaryCta: {
          label: "Explorar beneficios",
          href: "#trust-highlights",
        },
        media: null,
      },
      {
        id: "hero-slide-editorial",
        announcement: "Rutinas personalizadas para cada tipo de piel",
        eyebrow: "Selección editorial",
        title: "Cuidado dermatológico a tu medida",
        subtitle:
          "Recibe recomendaciones personalizadas basadas en tu tipo de piel y objetivos. Nuestros especialistas diseñan rutinas que realmente funcionan.",
        supportingBadge: "100% personalizado",
        primaryCta: {
          label: "Ver criterio editorial",
          href: "#editorial-guidance",
        },
        secondaryCta: {
          label: "Descubrir destacados",
          href: "#featured-products",
        },
        media: null,
      },
    ],
    spotlightCards: [
      {
        id: "hero-card-clarity",
        eyebrow: "Selección clínica",
        title: "Rutina de claridad diaria",
        href: "#featured-products",
        media: null,
      },
      {
        id: "hero-card-barrier",
        eyebrow: "Cuidado guiado",
        title: "Soporte para barrera y confort",
        href: "#featured-categories",
        media: null,
      },
      {
        id: "hero-card-editorial",
        eyebrow: "Contenido experto",
        title: "Explora criterio editorial y beneficios",
        href: "#editorial-guidance",
        media: null,
      },
    ],
  },
  featuredCampaign: {
    sectionId: "featured-campaign",
    eyebrow: "Colección exclusiva",
    title: "Descubre nuestra colección de cuidado dermatológico premium.",
    description:
      "Descubre nuestra selección premium de productos dermatológicos con precios especiales por temporada. Ediciones limitadas disponibles solo por tiempo reducido.",
    accentText: "Edición limitada",
    primaryCta: {
      label: "Ver productos",
      href: "#featured-products",
    },
    secondaryCta: {
      label: "Explorar categorías",
      href: "#featured-categories",
    },
    media: null,
  },
  featuredProducts: {
    sectionId: "featured-products",
    eyebrow: "Lo más vendido",
    title: "Los favoritos de nuestros pacientes",
    description:
      "Los productos más recomendados por nuestros dermatólogos para rutinas de cuidado diario. Resultados visibles respaldados por estudios clínicos.",
    cta: {
      label: "Ver todos los productos",
      href: "#contact-cta",
    },
    items: [
      {
        id: "product-clarity",
        name: "Rutina de claridad diaria",
        brand: "Dermatologika",
        description: "Rutina diaria que unifica tono y reduce manchas visibles en 4 semanas. Formulada con niacinamida y vitamina C estabilizada.",
        href: "#contact-cta",
        badge: "Destacado",
        price: 65,
        discountPrice: null,
        category: {
          id: "daily-protection",
          slug: "daily-protection",
          name: "Protección diaria",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-balance",
        name: "Balance hidratante",
        brand: "Dermatologika",
        description: "Hidratación equilibrada para pieles mixtas y sensibles sin sensación grasa. Ácido hialurónico de bajo peso molecular.",
        href: "#contact-cta",
        badge: "Más consultado",
        price: 63.15,
        discountPrice: null,
        category: {
          id: "barrier-support",
          slug: "barrier-support",
          name: "Reparación de barrera",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-renewal",
        name: "Renovación nocturna",
        brand: "Dermatologika",
        description: "Regeneración celular nocturna con ácidos suaves y péptidos reparadores. Despierta con piel visiblemente más luminosa.",
        href: "#contact-cta",
        badge: "Edición curada",
        price: 61.3,
        discountPrice: 57.9,
        category: {
          id: "post-procedure",
          slug: "post-procedure",
          name: "Cuidado post procedimiento",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-hydration",
        name: "Hidratación intensiva",
        brand: "Dermatologika",
        description: "Fórmula de hidratación profunda para pieles sensibles.",
        href: "#contact-cta",
        badge: "Nuevo",
        price: 68,
        discountPrice: 58.5,
        category: {
          id: "daily-protection",
          slug: "daily-protection",
          name: "Protección diaria",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-barrier",
        name: "Reparación de barrera avanzada",
        brand: "Dermatologika",
        description: "Reconstruye la barrera cutánea con ceramidas activas.",
        href: "#contact-cta",
        badge: "Más vendido",
        price: 72,
        discountPrice: 65,
        category: {
          id: "barrier-support",
          slug: "barrier-support",
          name: "Reparación de barrera",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-sunscreen",
        name: "Protector solar facial SPF 50",
        brand: "Dermatologika",
        description: "Protección UVA/UVB sin residuo blanco para uso diario.",
        href: "#contact-cta",
        badge: "Top",
        price: 55,
        discountPrice: 49,
        category: {
          id: "daily-protection",
          slug: "daily-protection",
          name: "Protección diaria",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-exfoliant",
        name: "Exfoliante enzimático suave",
        brand: "Dermatologika",
        description: "Elimina células muertas sin fricción mecánica.",
        href: "#contact-cta",
        badge: "Oferta",
        price: 48,
        discountPrice: 39.99,
        category: {
          id: "cleansers",
          slug: "cleansers",
          name: "Limpieza clínica",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-night",
        name: "Serum nocturno reparador",
        brand: "Dermatologika",
        description: "Serum concentrado para regeneración nocturna.",
        href: "#contact-cta",
        badge: "Destacado",
        price: 85,
        discountPrice: null,
        category: {
          id: "post-procedure",
          slug: "post-procedure",
          name: "Cuidado post procedimiento",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-cleanser",
        name: "Gel limpiador pH balanceado",
        brand: "Dermatologika",
        description: "Limpieza profunda que respeta el manto ácido de la piel.",
        href: "#contact-cta",
        badge: "Más consultado",
        price: 42,
        discountPrice: 38,
        category: {
          id: "cleansers",
          slug: "cleansers",
          name: "Limpieza clínica",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "product-calming",
        name: "Crema calmante post-procedimiento",
        brand: "Dermatologika",
        description: "Alivio inmediato para piel sensibilizada por tratamientos.",
        href: "#contact-cta",
        badge: "Edición curada",
        price: 78,
        discountPrice: 68,
        category: {
          id: "post-procedure",
          slug: "post-procedure",
          name: "Cuidado post procedimiento",
          href: "#contact-cta",
        },
        media: null,
      },
    ],
  },
  routinePromo: {
    sectionId: "routine-promo",
    eyebrow: "Rutinas completas",
    title: "Arma tu rutina paso a paso",
    description:
      "Completa tu ritual de cuidado con productos complementarios pensados para potenciar resultados. Arma combos y ahorra en tu tratamiento.",
    accentText: "Hasta 20% de descuento en combos",
    primaryCta: {
      label: "Ver rutinas",
      href: "#featured-categories",
    },
    secondaryCta: {
      label: "Contactar asesoría",
      href: "#trust-highlights",
    },
    media: null,
  },
  featuredCategories: {
    sectionId: "featured-categories",
    eyebrow: "Explora por necesidad",
    title: "Encuentra lo que tu piel necesita",
    description:
      "Navega por categorías diseñadas por nuestros especialistas para cada tipo de piel y condición. Desde limpieza diaria hasta recuperación post tratamiento.",
    cta: {
      label: "Recibir orientación gratuita",
      href: "#contact-cta",
    },
    items: [
      {
        id: "cleansers",
        name: "Limpieza clínica",
        description: "Rutinas de limpieza suave para piel sensible, grasa o sensibilizada.",
        href: "#contact-cta",
        media: null,
      },
      {
        id: "barrier-support",
        name: "Reparación de barrera",
        description: "Fórmulas orientadas a confort, equilibrio y recuperación visible.",
        href: "#contact-cta",
        media: null,
      },
      {
        id: "daily-protection",
        name: "Protección diaria",
        description: "Protección y mantenimiento diario dentro de una rutina constante.",
        href: "#contact-cta",
        media: null,
      },
      {
        id: "post-procedure",
        name: "Cuidado post procedimiento",
        description: "Recuperación y cuidado intensivo después de tratamientos dermatológicos. Ingredientes reparadores de acción inmediata.",
        href: "#contact-cta",
        media: null,
      },
    ],
  },
  routineProducts: {
    sectionId: "routine-products",
    eyebrow: "Complementá tu rutina",
    title: "Lo que no puede faltar en tu baño",
    description:
      "Productos esenciales para mantener resultados entre consultas con tu dermatólogo. La base de toda rutina de cuidado efectiva.",
    cta: {
      label: "Ver todos los complementos",
      href: "#editorial-guidance",
    },
    items: [
      {
        id: "routine-recovery",
        name: "Recuperación y confort",
        brand: "Dermatologika",
        description: "Kit de recuperación post-tratamiento con ingredientes calmantes de acción inmediata. Ideal después de peeling o láser.",
        href: "#contact-cta",
        badge: "Rutina guiada",
        price: 59.44,
        discountPrice: null,
        category: {
          id: "barrier-support",
          slug: "barrier-support",
          name: "Reparación de barrera",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "routine-defense",
        name: "Defensa diaria",
        brand: "Dermatologika",
        description: "Protección solar y antioxidantes para el cuidado diario de tu piel. Previene el envejecimiento prematuro causado por el sol.",
        href: "#contact-cta",
        badge: "Reposición",
        price: 57.59,
        discountPrice: null,
        category: {
          id: "daily-protection",
          slug: "daily-protection",
          name: "Protección diaria",
          href: "#contact-cta",
        },
        media: null,
      },
      {
        id: "routine-night",
        name: "Soporte nocturno",
        brand: "Dermatologika",
        description: "Limpieza profunda nocturna que prepara la piel para la regeneración celular. Elimina impurezas sin resecar.",
        href: "#contact-cta",
        badge: "Noche",
        price: 54.9,
        discountPrice: 49.9,
        category: {
          id: "cleansers",
          slug: "cleansers",
          name: "Limpieza clínica",
          href: "#contact-cta",
        },
        media: null,
      },
    ],
  },
  editorial: {
    sectionId: "editorial-guidance",
    eyebrow: "Criterio médico",
    title: "Dermatologika: ciencia al servicio de tu piel",
    description:
      "Nuestro equipo de dermatólogos selecciona y valida cada producto antes de incluirlo en nuestra tienda. Solo lo que realmente funciona.",
    accentText: "Respaldado por dermatólogos certificados",
    primaryCta: {
      label: "Ver beneficios",
      href: "#trust-highlights",
    },
    secondaryCta: {
      label: "Ir al cierre",
      href: "#contact-cta",
    },
    media: null,
    items: [
      {
        id: "editorial-1",
        title: "Selección médica",
        description: "Cada producto pasa por revisión de nuestro equipo médico antes de llegar a tu rutina. Sin excepciones.",
      },
      {
        id: "editorial-2",
        title: "Formulación eficaz",
        description: "Ingredientes con evidencia clínica y concentraciones terapéuticas reales. No promesas, resultados.",
      },
      {
        id: "editorial-3",
        title: "Acompañamiento continuo",
        description: "Accede a asesoría dermatológica gratuita para construir tu rutina ideal y mantener resultados a largo plazo.",
      },
    ],
  },
  trustHighlights: {
    sectionId: "trust-highlights",
    eyebrow: "Por qué elegirnos",
    title: "Tu piel en manos de especialistas",
    description:
      "Combinamos tecnología dermatológica de avanzada con un servicio personalizado que acompaña tu tratamiento de principio a fin.",
    items: [
      {
        id: "typed-content",
        title: "Productos validados",
        description: "Cada fórmula es evaluada por dermatólogos certificados antes de estar disponible en nuestra tienda.",
      },
      {
        id: "media-ready",
        title: "Envío a domicilio",
        description: "Recibe tu rutina en la puerta de tu casa con seguimiento en tiempo real. Entregas en 24-48 horas.",
      },
      {
        id: "server-boundary",
        title: "Asesoría gratuita",
        description: "Consulta con nuestros especialistas sin costo para personalizar tu tratamiento y resolver todas tus dudas.",
      },
    ],
  },
  cta: {
    sectionId: "contact-cta",
    eyebrow: "Empieza hoy",
    title: "Tu rutina de cuidado dermatológico empieza aquí",
    description:
      "Recibe asesoría personalizada, accede a promociones exclusivas y descubre productos que realmente funcionan. Tu piel lo merece.",
    primaryCta: {
      label: "Arma tu rutina",
      href: "#featured-categories",
    },
    secondaryCta: {
      label: "Habla con un especialista",
      href: "/admin/login",
    },
  },
};
